export { default as LoginPage } from './pages/LoginPage'
export { default as JoinPage } from './pages/JoinPage'
export { default as CompanyPage } from './pages/CompanyPage'
export { default as QuestionsPage } from './pages/QuestionsPage'
export { default as TeamPage } from './pages/TeamPage'
export { default as ProfilePage } from './pages/ProfilePage'
